package com.cloud.chatbot;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Provides utilities for working with timestamps.
 *
 * A timestamp is a string of a format that is easy to type. For example,
 * "1 2 23 456" represents the 1st of February 2023, at 4:56am.
 *
 * A pretty timestamp is a more complex string used for display purposes. It is
 * only meant to be generated by the program, not for a user to type in that
 * format. Eg the above time would become "1 Feb '23, 4:56am". If the minutes
 * are 00, then that part as well as the colon is omitted.
 */
public final class DateConverter {
    /**
     * Converts the specified timestamp into an Instant.
     *
     * @param timestamp The timestamp.
     */
    public static Instant timestampToInstant(String timestamp) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d M uu Hmm");

        LocalDateTime local = LocalDateTime.parse(timestamp, formatter);
        ZonedDateTime zoned = local.atZone(ZoneId.systemDefault());
        return zoned.toInstant();
    }

    /**
     * Converts the specified Instant into a pretty timestamp.
     *
     * @param instant the Instant.
     */
    public static String instantToPrettyTimestamp(Instant instant) {
        ZonedDateTime zoned = instant.atZone(ZoneId.systemDefault());

        String timestamp = DateTimeFormatter
                .ofPattern("d MMM ''uu, h")
                .format(zoned);

        // Only add minutes that are not 00
        if (zoned.getMinute() != 0) {
            timestamp += DateTimeFormatter
                    .ofPattern(":mm")
                    .format(zoned);
        }

        // Lowercase the AM/PM
        timestamp += DateTimeFormatter
                .ofPattern("a")
                .format(zoned)
                .toLowerCase();

        return timestamp;
    }
}
