package alcazar;

/**
 * Encapsulates a commands response
 */
public class Response {
    /** Response generated from a command*/
    private String result;
    /** Boolean to checker whether the command is exit*/
    private boolean isExit;
    /** The new data source location */
    private String changedFilePath;
    /** Boolean to check whether the calling command is ChangeDataSource */
    private boolean isFileChanging;

    /**
     * Constructs a new Response
     * @param result the result of the command
     * @param isExit whether the command is exit
     */
    public Response(String result, boolean isExit) {
        this.result = result;
        this.isExit = isExit;
        this.isFileChanging = false;
        this.changedFilePath = "";
    }

    /**
     * Evaluates and returns the result in this Response
     * @return The result in this Response
     */
    public String getResult() {
        return this.result;
    }

    /**
     * Evaluates whether this Response was generated from an Exit command
     * @return Boolean represent whether this Response is by an Exit command
     */

    public boolean isUserExiting() {
        return isExit;
    }

    /**
     * Evaluates whether this response was generated by ChangeFileCommand
     * @return Boolean to check whether this Response was created by a ChangeFileCommand
     */
    public boolean isFileChange() {
        return this.isFileChanging;
    }

    /**
     * Changes the changedFilePath to the passed filePath
     * @param filePath The file path to change the data Source to.
     */
    public void setFilePath(String filePath) {
        this.changedFilePath = filePath;
        this.isFileChanging = true;
    }

    /**
     * Evaluates and returns the changed file path for the data source.
     * @return The file path to the new data source
     */
    public String getFilePath() {
        return this.changedFilePath;
    }

}
