package dialogix.main;

import dialogix.command.Command;
import dialogix.exception.DialogixException;

/**
 * Represents the main class for the Dialogix application.
 */
public class Dialogix {
    private static final String filePath = "/data/dialogix.txt";
    private final Storage storage;
    private TaskList tasks;
    private final Ui ui;
    private boolean isExit = false;

    /**
     * Initializes the Dialogix application.
     */
    public Dialogix() {
        storage = new Storage(filePath);
        ui = new Ui();

        try {
            tasks = new TaskList(storage.load());
        } catch (DialogixException e) {
            System.out.println(e.getMessage());
            tasks = new TaskList();
        }
    }

    /**
     * Gets a response from the Dialogix application based on user input.
     *
     * @param input The user's input.
     * @return The response generated by the application.
     */
    public String getResponse(String input) {
        if (isExit) {
            return "";
        }

        try {
            ui.resetOutput();
            Command c = Parser.parse(input);
            c.execute(tasks, ui, storage);
            isExit = c.isExit();
            return ui.getOutput();
        } catch (DialogixException e) {
            return e.getMessage();
        }
    }
}
