package duke.command;

import duke.storage.Storage;
import duke.tasklist.TaskList;
import duke.ui.Ui;

/**
 * Represents a command that updates a specific field of a task in the task list.
 */
public class UpdateCommand extends Command {
    /** Number of the task to be mark as done from the task list */
    private int taskNumber;
    /** The field of the task to update. */
    private String field;
    /** The new value to set for the specified field. */
    private String newValue;

    /**
     * Creates an update command with the specified task number, field, and new value.
     *
     * @param taskNumber The number of the task to update in the task list.
     * @param field The field of the task to update.
     * @param newValue The new value to set for the specified field.
     */
    public UpdateCommand(int taskNumber, String field, String newValue) {
        this.taskNumber = taskNumber;
        this.field = field;
        this.newValue = newValue;
    }

    /**
     * Executes the update command.
     * Retrieves the task with the specified number from the task list
     * and updates the specified field with the new value.
     * Invokes the UI to display a message indicating the task has been updated.
     *
     * @param tasks The list of tasks to operate on.
     * @param ui The UI used to display the update message.
     * @param storage The storage mechanism used to persist tasks, not
     *                utilized in this method but available for future extensions.
     * @return The message generated by the UI indicating the task has been updated.
     */
    @Override
    public String execute(TaskList tasks, Ui ui, Storage storage) {
        tasks.updateTask(this.taskNumber, this.field, this.newValue);
        return ui.showUpdateText(tasks, this.taskNumber);
    }

    /**
     * Specifies that this command is not an exit command.
     *
     * @return false, as this command does not cause the program to exit.
     */
    @Override
    public boolean isExit() {
        return false;
    }
}

