package duke.utils;

import java.util.List;

/**
 * The Response class represents a response generated by the Duke application
 * to provide feedback to the user.
 */
public class Response {
    protected static final Response GREETINGS = Response.greeting();
    protected static final Response TERMINATE = Response.terminate();
    private static final String LINE = "    ____________________________________________________________\n";
    private static final String TAB = "    ";
    private String messageOutput;

    private Response() {
        this.messageOutput = "";
    }

    private void add(String message) {
        this.messageOutput += Response.TAB + message + "\n";
    }

    /**
     * Generates a response with a single message.
     *
     * @param message The message to be included in the response.
     * @return A Response object containing the specified message.
     */
    protected static Response generate(String message) {
        Response response = new Response();
        response.add(message);
        return response;
    }

    /**
     * Generates a response with an array of messages.
     *
     * @param messageArray An array of messages to be included in the response.
     * @return A Response object containing the specified messages.
     */
    protected static Response generate(String[] messageArray) {
        Response response = new Response();
        for (int i = 0; i < messageArray.length; i++) {
            response.add(messageArray[i]);
        }
        return response;
    }

    /**
     * Generates a response with a list of messages.
     *
     * @param messageList A list of messages to be included in the response.
     * @return A Response object containing the specified messages.
     */
    protected static Response generate(List<String> messageList) {
        Response response = new Response();
        for (String s : messageList) {
            response.add(s);
        }
        return response;
    }

    /**
     * Generates a greeting response.
     *
     * @return A Response object with a standard greeting message.
     */
    protected static Response greeting() {
        Response response = new Response();
        response.add("Hello! I'm Duke");
        response.add("What can I do for you?");
        return response;
    }

    /**
     * Generates a termination response.
     *
     * @return A Response object with a standard termination message.
     */
    protected static Response terminate() {
        Response response = new Response();
        response.add("Bye. Hope to see you again soon!");
        return response;
    }

    /**
     * Returns a string representation of the response, including message content.
     *
     * @return A string representation of the response.
     */
    @Override
    public String toString() {
        return Response.LINE + this.messageOutput + Response.LINE;
    }
}
