package avalon;

import avalon.task.TaskList;
import avalon.utility.Parser;
import avalon.utility.Storage;
import avalon.utility.Ui;

/**
 * The main class for the Duke ChatBot (Avalon).
 */
public class Avalon {

    private final Ui ui;
    private final Storage storage;
    private final TaskList taskList;

    @SuppressWarnings("checkstyle:ModifierOrder")
    public String filepath = "./data/Avalon.txt";



    /**
     * Constructs an Avalon instance with the specified file path for task storage.
     */
    public Avalon() {
        this.ui = new Ui();
        this.storage = new Storage(filepath);
        this.taskList = new TaskList();
        //storage.loadTasks(this.taskList);
    }

    /**
     * Gets a response from the ChatBot based on the user input.
     *
     * @param input The user's input.
     * @return The response generated by the ChatBot.
     */
    public String getResponse(String input) {
        ui.clearOutput();

        return Parser.processCommand(input, taskList, storage, ui);
    }
}
