package duke.main;

import duke.command.*;
import duke.exception.*;

import java.io.IOException;

/**
 * The main class for Duke chatbot application.
 */
public class Duke {

    private static final String FILE_PATH = "./tasks.txt";
    private Storage storage;
    private TaskList tasks;
    private Ui ui;

    /**
     * Constructs a Duke object with the given file path.
     */
    public Duke() {
        ui = new Ui();
        assert !FILE_PATH.isEmpty() : "There should be a valid filepath";
        storage = new Storage(FILE_PATH);
        try {
            tasks = new TaskList(storage.load());
        } catch (IOException e) {
            ui.showLoadingError();
            tasks = new TaskList();
        }
    }

    /**
     * Initializes the chatbot and displays the greeting message.
     *
     * @return The initial message from the chatbot.
     */
    public String initialise() {
        ui.showHeader();
        ui.showReminders(tasks.getReminders());
        ui.showGreeting();
        return ui.getCurrentMessage();
    }

    /**
     * Runs the chatbot application by processing the user input.
     *
     * @param input The input provided by the user.
     */
    public void run(String input) {
        try {
            Command c = Parser.parse(input);
            c.execute(tasks, ui, storage);
        } catch (DukeException e) {
            ui.showError(e.getMessage());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Gets the response from the chatbot for the given input.
     *
     * @param input The input provided by the user.
     * @return The response generated by the chatbot.
     */
    public String getResponse(String input) {
        run(input);
        return ui.getCurrentMessage();
    }
}
