package devybot;

import devybot.exceptions.DevyBotException;
import devybot.util.Parser;
import devybot.util.Storage;
import devybot.util.TaskList;
import devybot.util.Ui;

public class DevyBot {
    private Storage storage;
    private TaskList tasks;

    public DevyBot() {
        this.initialize("data/tasks.txt");
    }

    private void initialize(String filePath) {
        this.storage = new Storage(filePath);
        try {
            this.tasks = new TaskList(storage.loadTasksFromFile());
        } catch (DevyBotException e) {
            Ui.showMessage(e.getMessage());
            this.tasks = new TaskList();
        }
    }

    protected String getResponse(String input) {
        StringBuilder response = new StringBuilder();

        try {
            Parser.parse(input, tasks);
            storage.saveTasksToFile(tasks);

            // Capture messages generated by Parser and storage
            String parserMessage = Ui.captureOutput(); // You'll need to implement this in Ui
            response.append(parserMessage);

        } catch (DevyBotException e) {
            String errorMessage = e.getMessage();
            response.append(errorMessage);
        }

        return response.toString();
    }

}
