package devybot;

import devybot.exceptions.DevyBotException;

import devybot.util.Parser;
import devybot.util.Storage;
import devybot.util.TaskList;
import devybot.util.Ui;

/**
 * The DevyBot class represents a chatbot application for managing tasks.
 */
public class DevyBot {
    private Storage storage;
    private TaskList tasks;

    /**
     * Initializes a new instance of DevyBot with the default data file path.
     */
    public DevyBot() {
        this.initialize("data/tasks.txt");
    }

    private void initialize(String filePath) {
        this.storage = new Storage(filePath);
        try {
            this.tasks = new TaskList(storage.loadTasksFromFile());
        } catch (DevyBotException e) {
            Ui.showMessage(e.getMessage());
            this.tasks = new TaskList();
        }
    }

    /**
     * Retrieves a response from DevyBot based on the user input.
     *
     * @param input The user input.
     * @return A response generated by DevyBot.
     */
    protected String getResponse(String input) {
        StringBuilder response = new StringBuilder();

        try {
            Parser.parseInputs(input, tasks);
            storage.saveTasksToFile(tasks);

            // Capture messages generated by Parser and storage
            String parserMessage = Ui.captureOutput();
            assert parserMessage.length() > 0 : "Parser should have generated a message";

            response.append(parserMessage);
        } catch (DevyBotException e) {
            String errorMessage = e.getMessage();
            response.append(errorMessage);
        }

        return response.toString();
    }
}
