package catbot.internal;

import java.util.function.Consumer;

/**
 * Object that parses a String using a predefined pattern, and has a default behaviour if the pattern does not apply.
 *
 * @param <T> type of output generated by the String if the pattern applies, to be fed to a Consumer.
 */
public interface CommandPattern<T> {

    /**
     * Runs the given Consumer if the pattern applies to the given String, feeding the output generated to the Consumer.
     * Otherwise, runs the default behaviour.
     *
     * @param args String to apply the pattern to.
     * @param consumer Consumer that accepts the output generated by successful pattern application.
     */
    void ifParsableElseDefault(String args, Consumer<T> consumer);

}
