package URBOI_PACKIN;

import URBOI_PACKIN.Storage.Storage;
import URBOI_PACKIN.TaskTypes.Deadline;
import URBOI_PACKIN.TaskTypes.Event;
import URBOI_PACKIN.TaskTypes.Todo;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;
import java.util.ArrayList;
import java.io.*;

import static URBOI_PACKIN.Storage.Storage.loadTasksFromFile;
import static URBOI_PACKIN.Storage.Storage.saveTasksToFile;

public class ResponseController {
    //private static final String FILE_PATH = "src/main/java/tasks.txt";
    private static final String FILE_PATH = "tasks.txt/";

    /**
     * Process user input and generate a response.
     *
     * @param command The user's input command.
     * @return A response generated by URBOI.
     */
    public String getResponse(String command) {
        ArrayList<Task> tasks = new ArrayList<>(100);
        loadTasksFromFile(tasks);
        StringBuilder response = new StringBuilder();
        try{
            if (command.equalsIgnoreCase("bye")) {
                response.append("Bye. Hope to see you again soon!");
            } else if (command.equalsIgnoreCase("list")) {
                response.append("Here are the tasks in your list:\n");
                for (int i = 0; i < tasks.size(); i++) {
                    response.append((i + 1) + ". " + tasks.get(i) + "\n");
                }
            } else if (command.startsWith("todo")) {
                String description = command.substring(5).trim();
                if (description.isEmpty()) {
                    throw new DukeException("The description of a todo cannot be empty.");
                }
                tasks.add(new Todo(description));
                response.append("Got it. I've added this task:\n  " + tasks.get(tasks.size() - 1));
                response.append("Now you have " + tasks.size() + " tasks in the list.");
            } else if (command.startsWith("deadline")) {
                // Parse the date and time in the format d/M/yyyy HHmm
                String[] parts = command.split(" /by ");
                if (parts.length < 2) {
                    throw new DukeException("URBOI_PACKIN.TaskTypes.Deadline command must include a date.");
                }
                String description = parts[0].substring(9).trim();
                LocalDateTime dateTime = LocalDateTime.parse(parts[1], DateTimeFormatter.ofPattern("d/M/yyyy HHmm"));

                tasks.add(new Deadline(description, dateTime));
                response.append("Got it. I've added this task:\n  " + tasks.get(tasks.size() - 1));
                response.append("Now you have " + tasks.size() + " tasks in the list.");
            } else if (command.startsWith("event")) {
                String description = command.substring(6, command.indexOf("/from")).trim();
                String from = command.substring(command.indexOf("/from") + 6, command.indexOf("/to")).trim();
                String to = command.substring(command.indexOf("/to") + 4).trim();
                tasks.add(new Event(description, from, to));
                response.append("Got it. I've added this task:\n  " + tasks.get(tasks.size() - 1));
                response.append("Now you have " + tasks.size() + " tasks in the list.");
            } else if (command.startsWith("mark")) {
                int index = Integer.parseInt(command.split(" ")[1]) - 1;
                if (index >= 0 && index < tasks.size()) {
                    tasks.get(index).markDone();
                    response.append("Nice! I've marked this task as done:\n  " + tasks.get(index));
                } else {
                    response.append("Invalid task index.");
                }
            } else if (command.startsWith("unmark")) {
                int index = Integer.parseInt(command.split(" ")[1]) - 1;
                if (index >= 0 && index < tasks.size()) {
                    tasks.get(index).markNotDone();
                    response.append("OK, I've marked this task as not done yet:\n  " + tasks.get(index));
                } else {
                    response.append("Invalid task index.");
                }
            }  else if (command.startsWith("delete")) {
                int index = Integer.parseInt(command.split(" ")[1]) - 1;
                if (index >= 0 && index < tasks.size()) {
                    Task removedTask = tasks.remove(index);
                    response.append("Noted. I've removed this task:\n  " + removedTask);
                    response.append("Now you have " + tasks.size() + " tasks in the list.");
                } else {
                    response.append("Invalid task index.");
                }
            } else if (command.startsWith("find")) {
                String keyword = command.substring(5).trim();
                findTasks(tasks, keyword);
            } else {
                throw new DukeException("I'm sorry, but I don't know what that means :-(");
            }
            saveTasksToFile(tasks);
        } catch (DukeException e) {
            response.append("☹ OOPS!!! " + e.getMessage());
        }
        return response.toString();
    }


    private static void findTasks(ArrayList<Task> tasks, String keyword) {
        System.out.println("Here are the matching tasks in your list:");
        int count = 0;
        for (int i = 0; i < tasks.size(); i++) {
            Task task = tasks.get(i);
            if (task.getDescription().contains(keyword)) {
                System.out.println((count + 1) + ". " + task);
                count++;
            }
        }
        if (count == 0) {
            System.out.println("No matching tasks found.");
        }
    }
}


/**
 * Custom exception class for URBOI_PACKIN.ResponseController-specific exceptions.
 */
class DukeException extends Exception {
    public DukeException(String message) {
        super(message);
    }
}